title:              Surina's DS Blog
email:              surinasrivastava@gmail.com
description:        Learn a new fun fact!
author:             Surina Srivastava
baseurl:            "dsblog"
url:                "https://Surina19.github.io"

# Social Profiles
twitter_username:   
github_username:    Surina19
facebook_username:  
instagram_username:  Surina.19
linkedin_username: www.linkedin.com/in/surina-srivastava-12b450270

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
